config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'main#index'
  post 'create', to: 'main#create_tweet', as: 'create_tweet'
  post 'like/:tweet', to: 'main#like_tweet', as: 'like_tweet'
  post 'follow/:friend', to: 'main#follow', as: 'follow_user'
  post 'unfollow/:friend', to: 'main#unfollow', as: 'unfollow_user'
  post 'unlike/:tweet', to: 'main#unlike_tweet', as: 'unlike_tweet'
  post 'retweet/:tweet', to: 'main#retweet', as: 'retweet'
  get 'show/:tweet', to: 'main#show', as: 'show'
  get 'user/:user', to: 'main#userprofile', as: 'userprofile'
  get 'tweets/:user', to: 'main#usertweets', as: 'usertweets'
  get 'mytweets', to: 'main#mytweets'
  get 'myprofile', to: 'main#myprofile'
  get 'followers', to: 'main#listfollower'
  get 'following', to: 'main#listfollowing'
  get 'search', to: 'main#search', as: 'search'

  get "api/news"
  get "api/:date1/:date2", to: "api#tweetsbydate"
  post "api/new_tweet"
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Index", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      
  <% if user_signed_in? %>
 
    <%= link_to 'Mis Tweets', mytweets_path , class:"nav-link"%>  
  
    <%= link_to "Logout", destroy_user_session_path, { method: :delete } %> 
   
    <%= link_to 'Following', following_path, class:"nav-link" %> 

  <% else %>
    <%= link_to 'Iniciar session', new_user_session_path, class:"nav-link" %>
    <%= link_to 'Registrarse', new_user_registration_path, class:"nav-link" %>
    <%= link_to 'Index', root_path , class:"nav-link"%>
  <% end %>
</div>

<div class="text-right">
  <%= form_tag search_path, method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag 'Buscar' %>
  <% end %>

</ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</html>